import { readdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

import { ISSUE_NUMBER, RECORD_NUMBER } from '../citations'

/*
 * WHAT A VENDORED FILE MAY SAY ABOUT ITSELF.
 *
 * These files are regenerated by the component CLI. Two rules govern them,
 * and this holds the second:
 *
 *   1. They stay pristine unless a divergence states its reason in a header —
 *      the vendoring rule. Unstated drift is a defect, because a re-vendor
 *      silently reverts it and nobody knows what was lost.
 *   2. That reason may not be a NUMBER. A record number belongs to the
 *      repository that assigned it, and this tree is consumed as source: a
 *      deployment reading `ADR 0014` in a file it shares with this template
 *      resolves it against ITS OWN records, where 0014 is a different
 *      decision or none at all. The reader ends up at the wrong page, or at a
 *      page that does not exist, and believes they have the reason.
 *
 * So a header names the decision in words. "Allowed only with a stated
 * reason" travels; "ADR 0014" does not.
 *
 * A deployment's own gate already refuses these citations in the files it
 * shares — sixteen of them arrived here in one pass and were caught only
 * downstream, after release. The rule is cheaper to hold where the files are
 * written.
 *
 * The matchers live in `src/citations.ts`, because the issue-number half of
 * this rule is held across the whole of `src/` by `src/citations.test.ts`.
 * One definition of what a citation is, two guards that read it.
 */

const UI = join(process.cwd(), 'src/components/ui')

function uiFiles(): string[] {
  return readdirSync(UI).filter((name) => name.endsWith('.tsx'))
}

describe('a vendored file names the decision, never the number', () => {
  it('cites no record number', () => {
    const offenders = uiFiles().flatMap((name) => {
      const lines = readFileSync(join(UI, name), 'utf8').split('\n')
      return lines.flatMap((line, index) =>
        RECORD_NUMBER.test(line) ? [`ui/${name}:${index + 1}: ${line.trim()}`] : [],
      )
    })
    expect(
      offenders,
      `A record number resolves against the READER's repository, not this one:\n${offenders.join('\n')}`,
    ).toEqual([])
  })

  it('cites no issue number', () => {
    const offenders = uiFiles().flatMap((name) => {
      const lines = readFileSync(join(UI, name), 'utf8').split('\n')
      return lines.flatMap((line, index) =>
        ISSUE_NUMBER.test(line) ? [`ui/${name}:${index + 1}: ${line.trim()}`] : [],
      )
    })
    expect(
      offenders,
      `An issue number is this repository's queue, and a deployment reading it lands in its own:\n${offenders.join('\n')}`,
    ).toEqual([])
  })

  it('reads a citation when there is one, so the guard is not vacuous', () => {
    // The rule is only worth holding if it can fail. These are the spellings
    // that reached a release before it existed.
    expect(RECORD_NUMBER.test(' * DIVERGENCE from the vendored source (ADR 0014)')).toBe(true)
    expect(RECORD_NUMBER.test(' * controls are primary, not brand (ADR 0008).')).toBe(true)
    expect(RECORD_NUMBER.test('adr-14')).toBe(true)
    // The issue-number half of the same claim is exercised in
    // `src/citations.test.ts`, which is where a fixture may spell one out.
  })
})
