// GENERATED by scripts/generate_sample_blueprint.mjs — edit the generator, not this file.
//
// The template's sample content is the META-BLUEPRINT: the service blueprint
// of this template itself. One lifecycle (Blueprint Kit Adoption), four phases
// (Discover → Adopt → Map → Operate, Operate looping back to Map), five
// scenarios covering the kit's real flows — discovery, the zero-config vs
// Supabase first run (two genuinely divergent paths), the sb:map pipeline,
// sb:slice presentation, and the audit/whatif stewardship loop. Every cell
// is a true statement about how the kit behaves, so the sample doubles as
// documentation. Registered as the offline fallback content in
// src/data/blueprintFallbacks.ts and src/types/nav.ts; the matching database
// seed is generated into supabase/seed.sql.
//
// Dimensions:
//   Discover the kit · First visit: 6 lanes, 8 steps, 23 cells, 10 triggers
//   Clone & first run · No-database run: 7 lanes, 12 steps, 35 cells, 13 triggers
//   Clone & first run · Supabase run: 7 lanes, 12 steps, 38 cells, 15 triggers
//   Map your service · Guided mapping: 8 lanes, 16 steps, 46 cells, 14 triggers
//   Review & present · Stakeholder readout: 6 lanes, 9 steps, 15 cells, 7 triggers
//   Keep it true · Stewardship loop: 6 lanes, 11 steps, 18 cells, 8 triggers

import type { BlueprintData } from '@/types/blueprint'
import type { Slice, SliceItem } from '@/types/database'

export const SAMPLE_LIFECYCLE_ID = 'f0000000-0000-4000-8000-000000000010'

export type SamplePhase = {
  id: string
  name: string
  description: string
  order_position: number
  loops_to_phase_id: string | null
}

export const SAMPLE_PHASES: SamplePhase[] = [
  {"id":"f0000000-0000-4000-8000-000700010000","name":"Discover","description":"The adopter finds the kit and decides it is worth an afternoon.","order_position":1,"loops_to_phase_id":null},
  {"id":"f0000000-0000-4000-8000-000700020000","name":"Adopt","description":"The kit goes from repository to running app on the adopter’s machine.","order_position":2,"loops_to_phase_id":null},
  {"id":"f0000000-0000-4000-8000-000700030000","name":"Map","description":"sb:map turns the adopter’s own service into a validated, imported blueprint.","order_position":3,"loops_to_phase_id":null},
  {"id":"f0000000-0000-4000-8000-000700040000","name":"Operate","description":"The blueprint stays true through audits, what-ifs, slices, and agent sessions — and loops back to Map when the service changes.","order_position":4,"loops_to_phase_id":"f0000000-0000-4000-8000-000700030000"},
]

export type SampleScenario = {
  id: string
  phase_id: string
  name: string
  description: string
  order_position: number
  /** Client-vocabulary view type for the offline nav. */
  view_type: 'single' | 'stacked'
  path_ids: string[]
}

export const SAMPLE_SCENARIOS: SampleScenario[] = [
  {"id":"f0000000-0000-4000-8000-100000000001","phase_id":"f0000000-0000-4000-8000-000700010000","name":"Discover the kit","description":"A first visit: the repository pitch, the live example, the model figures, and the decision to try it.","order_position":1,"view_type":"single","path_ids":["f0000000-0000-4000-8000-110000000000"]},
  {"id":"f0000000-0000-4000-8000-200000000001","phase_id":"f0000000-0000-4000-8000-000700020000","name":"Clone & first run","description":"Two ways to a running app: the zero-config no-database run, and the same journey backed by a local Supabase stack.","order_position":1,"view_type":"stacked","path_ids":["f0000000-0000-4000-8000-210000000000","f0000000-0000-4000-8000-220000000000"]},
  {"id":"f0000000-0000-4000-8000-300000000001","phase_id":"f0000000-0000-4000-8000-000700030000","name":"Map your service","description":"The sb:map pipeline: elicitation → draft → validation → adversarial review → per-scenario sign-off → import → deploy.","order_position":1,"view_type":"single","path_ids":["f0000000-0000-4000-8000-310000000000"]},
  {"id":"f0000000-0000-4000-8000-400000000001","phase_id":"f0000000-0000-4000-8000-000700040000","name":"Review & present","description":"sb:slice takes one stakeholder view out of the blueprint and carries it into presentation mode and PDF.","order_position":1,"view_type":"single","path_ids":["f0000000-0000-4000-8000-410000000000"]},
  {"id":"f0000000-0000-4000-8000-500000000001","phase_id":"f0000000-0000-4000-8000-000700040000","name":"Keep it true","description":"The stewardship loop: sb:audit finds drift, sb:whatif traces the fix, the re-import lands it — then the loop runs again.","order_position":2,"view_type":"single","path_ids":["f0000000-0000-4000-8000-510000000000"]},
]

export const SAMPLE_DISCOVER_KIT_VISIT_PATH_FALLBACK: BlueprintData = {
  path: {"id":"f0000000-0000-4000-8000-110000000000","name":"First visit","description":"Reading the repo end to end, from pitch to decision.","note":null,"path_type":"happy"},
  layers: [
    {"id":"f0000000-0000-4000-8000-110100000000","name":"Journey snapshots","role":"visual","row_position":0},
    {"id":"f0000000-0000-4000-8000-110100010000","name":"Adopter","role":"customer_actions","row_position":1},
    {"id":"f0000000-0000-4000-8000-110100020000","name":"Repo front door","role":"frontstage_actions","row_position":2},
    {"id":"f0000000-0000-4000-8000-110100030000","name":"Live demo","role":"frontstage_tech","row_position":3},
    {"id":"f0000000-0000-4000-8000-110100040000","name":"README & guides","role":"support_systems","row_position":4},
    {"id":"f0000000-0000-4000-8000-110100050000","name":"Maintainers","role":"backstage_actions","row_position":5},
  ],
  steps: [
    {"id":"f0000000-0000-4000-8000-100200010000","name":"Land on the repository","column_position":1},
    {"id":"f0000000-0000-4000-8000-100200020000","name":"Read the pitch","column_position":2},
    {"id":"f0000000-0000-4000-8000-100200030000","name":"Open the live demo","column_position":3},
    {"id":"f0000000-0000-4000-8000-100200040000","name":"Walk the model figures","column_position":4},
    {"id":"f0000000-0000-4000-8000-100200050000","name":"Meet the four skills","column_position":5},
    {"id":"f0000000-0000-4000-8000-100200060000","name":"Skim the guides","column_position":6},
    {"id":"f0000000-0000-4000-8000-100200070000","name":"Weigh the fit","column_position":7},
    {"id":"f0000000-0000-4000-8000-100200080000","name":"Decide to adopt","column_position":8},
  ],
  cells: [
    {"id":"f0000000-0000-4000-8000-110300000001","layer_id":"f0000000-0000-4000-8000-110100000000","step_id":"f0000000-0000-4000-8000-100200010000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300000003","layer_id":"f0000000-0000-4000-8000-110100000000","step_id":"f0000000-0000-4000-8000-100200030000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300000005","layer_id":"f0000000-0000-4000-8000-110100000000","step_id":"f0000000-0000-4000-8000-100200050000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300000008","layer_id":"f0000000-0000-4000-8000-110100000000","step_id":"f0000000-0000-4000-8000-100200080000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300010001","layer_id":"f0000000-0000-4000-8000-110100010000","step_id":"f0000000-0000-4000-8000-100200010000","content":"Lands on the GitHub repository, usually from a link or a search","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300010002","layer_id":"f0000000-0000-4000-8000-110100010000","step_id":"f0000000-0000-4000-8000-100200020000","content":"Reads the README pitch: the blueprint stops being a poster and becomes a database","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300010003","layer_id":"f0000000-0000-4000-8000-110100010000","step_id":"f0000000-0000-4000-8000-100200030000","content":"Clicks through the example deployment and flips between path variants","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300010004","layer_id":"f0000000-0000-4000-8000-110100010000","step_id":"f0000000-0000-4000-8000-100200040000","content":"Follows the hierarchy figure from lifecycle to phase to scenario to path","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300010005","layer_id":"f0000000-0000-4000-8000-110100010000","step_id":"f0000000-0000-4000-8000-100200050000","content":"Reads what each of the four skills is for and where it ends","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300010006","layer_id":"f0000000-0000-4000-8000-110100010000","step_id":"f0000000-0000-4000-8000-100200060000","content":"Opens the guide that matches their role","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300010007","layer_id":"f0000000-0000-4000-8000-110100010000","step_id":"f0000000-0000-4000-8000-100200070000","content":"Checks the stack, the license, and what a deployment would expose","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300010008","layer_id":"f0000000-0000-4000-8000-110100010000","step_id":"f0000000-0000-4000-8000-100200080000","content":"Decides to clone the template and try it on a real service","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300020002","layer_id":"f0000000-0000-4000-8000-110100020000","step_id":"f0000000-0000-4000-8000-100200020000","content":"Positions the queryable blueprint against the static artifact it replaces","picture":null,"description":null,"links":[{"type":"url","label":"README — why a queryable blueprint","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/README.md"}]},
    {"id":"f0000000-0000-4000-8000-110300020003","layer_id":"f0000000-0000-4000-8000-110100020000","step_id":"f0000000-0000-4000-8000-100200030000","content":"Links the live example, with the note that nothing in the repo depends on it","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300020005","layer_id":"f0000000-0000-4000-8000-110100020000","step_id":"f0000000-0000-4000-8000-100200050000","content":"Summarizes each skill in one table row: what it is for, where it ends","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300020007","layer_id":"f0000000-0000-4000-8000-110100020000","step_id":"f0000000-0000-4000-8000-100200070000","content":"States the exposure note: deployed tables are publicly readable","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300030003","layer_id":"f0000000-0000-4000-8000-110100030000","step_id":"f0000000-0000-4000-8000-100200030000","content":"Example deployment\nPhase overview canvas","picture":null,"description":null,"links":[{"type":"tech_description","label":"Example deployment","description":"README links a deployment of the stock renderer, flagged as an example and not a dependency — nothing in this repo needs it."}]},
    {"id":"f0000000-0000-4000-8000-110300030004","layer_id":"f0000000-0000-4000-8000-110100030000","step_id":"f0000000-0000-4000-8000-100200040000","content":"Cell detail panel\nTrigger arrows","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-110300040002","layer_id":"f0000000-0000-4000-8000-110100040000","step_id":"f0000000-0000-4000-8000-100200020000","content":"README.md","picture":null,"description":null,"links":[{"type":"url","label":"README.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/README.md"}]},
    {"id":"f0000000-0000-4000-8000-110300040004","layer_id":"f0000000-0000-4000-8000-110100040000","step_id":"f0000000-0000-4000-8000-100200040000","content":"guide/01 — the blueprint model\ndocs/assets figures","picture":null,"description":null,"links":[{"type":"url","label":"guide/01 — The blueprint model","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/docs/guide/01-the-blueprint-model.md"}]},
    {"id":"f0000000-0000-4000-8000-110300040006","layer_id":"f0000000-0000-4000-8000-110100040000","step_id":"f0000000-0000-4000-8000-100200060000","content":"guide/02 — using it in practice\nguide/04 — operations","picture":null,"description":null,"links":[{"type":"url","label":"guide/02 — Using it in practice","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/docs/guide/02-using-it-in-practice.md"},{"type":"url","label":"guide/04 — Operations","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/docs/guide/04-operations.md"}]},
    {"id":"f0000000-0000-4000-8000-110300040007","layer_id":"f0000000-0000-4000-8000-110100040000","step_id":"f0000000-0000-4000-8000-100200070000","content":"LICENSE\nsupabase/DATABASE.md","picture":null,"description":null,"links":[{"type":"url","label":"supabase/DATABASE.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/supabase/DATABASE.md"}]},
    {"id":"f0000000-0000-4000-8000-110300050007","layer_id":"f0000000-0000-4000-8000-110100050000","step_id":"f0000000-0000-4000-8000-100200070000","content":"Record what shipped in CHANGELOG.md, release by release","picture":null,"description":null,"links":[{"type":"url","label":"CHANGELOG.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/CHANGELOG.md"}]},
  ],
  triggers: [
    {"id":"f0000000-0000-4000-8000-110400010000","source_cell_id":"f0000000-0000-4000-8000-110300010001","target_cell_id":"f0000000-0000-4000-8000-110300010002"},
    {"id":"f0000000-0000-4000-8000-110400020000","source_cell_id":"f0000000-0000-4000-8000-110300010002","target_cell_id":"f0000000-0000-4000-8000-110300010003"},
    {"id":"f0000000-0000-4000-8000-110400030000","source_cell_id":"f0000000-0000-4000-8000-110300010003","target_cell_id":"f0000000-0000-4000-8000-110300010004"},
    {"id":"f0000000-0000-4000-8000-110400040000","source_cell_id":"f0000000-0000-4000-8000-110300010004","target_cell_id":"f0000000-0000-4000-8000-110300010005"},
    {"id":"f0000000-0000-4000-8000-110400050000","source_cell_id":"f0000000-0000-4000-8000-110300010005","target_cell_id":"f0000000-0000-4000-8000-110300010006"},
    {"id":"f0000000-0000-4000-8000-110400060000","source_cell_id":"f0000000-0000-4000-8000-110300010006","target_cell_id":"f0000000-0000-4000-8000-110300010007"},
    {"id":"f0000000-0000-4000-8000-110400070000","source_cell_id":"f0000000-0000-4000-8000-110300010007","target_cell_id":"f0000000-0000-4000-8000-110300010008"},
    {"id":"f0000000-0000-4000-8000-110400080000","source_cell_id":"f0000000-0000-4000-8000-110300020002","target_cell_id":"f0000000-0000-4000-8000-110300030003","label":"See it live"},
    {"id":"f0000000-0000-4000-8000-110400090000","source_cell_id":"f0000000-0000-4000-8000-110300010006","target_cell_id":"f0000000-0000-4000-8000-110300040006"},
    {"id":"f0000000-0000-4000-8000-110400100000","source_cell_id":"f0000000-0000-4000-8000-110300010008","target_cell_id":"f0000000-0000-4000-8000-110300020007","kind":"needs","note":"The decision to adopt depends on knowing what a public deployment exposes."},
  ],
}

export const SAMPLE_FIRST_RUN_NODB_PATH_FALLBACK: BlueprintData = {
  path: {"id":"f0000000-0000-4000-8000-210000000000","name":"No-database run","description":"Zero config: clone, install, run — the bundled sample content renders with no environment at all.","note":null,"path_type":"happy"},
  layers: [
    {"id":"f0000000-0000-4000-8000-210100000000","name":"Journey snapshots","role":"visual","row_position":0},
    {"id":"f0000000-0000-4000-8000-210100010000","name":"Adopter","role":"customer_actions","row_position":1},
    {"id":"f0000000-0000-4000-8000-210100020000","name":"App feedback","role":"frontstage_actions","row_position":2},
    {"id":"f0000000-0000-4000-8000-210100030000","name":"App UI","role":"frontstage_tech","row_position":3},
    {"id":"f0000000-0000-4000-8000-210100040000","name":"Data layer","role":"backstage_actions","row_position":4},
    {"id":"f0000000-0000-4000-8000-210100050000","name":"Terminal & scripts","role":"backstage_tech","row_position":5},
    {"id":"f0000000-0000-4000-8000-210100060000","name":"样例数据 · Sample data","role":"support_systems","row_position":6},
  ],
  steps: [
    {"id":"f0000000-0000-4000-8000-200200010000","name":"Clone the repository","column_position":1},
    {"id":"f0000000-0000-4000-8000-200200020000","name":"Install dependencies","column_position":2},
    {"id":"f0000000-0000-4000-8000-200200030000","name":"Configure the environment","column_position":3},
    {"id":"f0000000-0000-4000-8000-200200040000","name":"Prepare the database","column_position":4},
    {"id":"f0000000-0000-4000-8000-200200050000","name":"Start the dev server","column_position":5},
    {"id":"f0000000-0000-4000-8000-200200060000","name":"Open the app","column_position":6},
    {"id":"f0000000-0000-4000-8000-200200070000","name":"Walk the sample content","column_position":7},
    {"id":"f0000000-0000-4000-8000-200200080000","name":"Compare the sample paths","column_position":8},
    {"id":"f0000000-0000-4000-8000-200200090000","name":"Open a demo slice","column_position":9},
    {"id":"f0000000-0000-4000-8000-200200100000","name":"Run the test suite","column_position":10},
    {"id":"f0000000-0000-4000-8000-200200110000","name":"Smoke the agent harness","column_position":11},
    {"id":"f0000000-0000-4000-8000-200200120000","name":"Deploy a preview","column_position":12},
  ],
  cells: [
    {"id":"f0000000-0000-4000-8000-210300000001","layer_id":"f0000000-0000-4000-8000-210100000000","step_id":"f0000000-0000-4000-8000-200200010000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300000006","layer_id":"f0000000-0000-4000-8000-210100000000","step_id":"f0000000-0000-4000-8000-200200060000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300000008","layer_id":"f0000000-0000-4000-8000-210100000000","step_id":"f0000000-0000-4000-8000-200200080000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300000012","layer_id":"f0000000-0000-4000-8000-210100000000","step_id":"f0000000-0000-4000-8000-200200120000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010001","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200010000","content":"Clones BilLogic/agentic-service-blueprinting from GitHub","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010002","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200020000","content":"Runs npm install","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010003","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200030000","content":"Skips .env entirely — the first run needs no environment","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010005","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200050000","content":"Runs npm run dev","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010006","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200060000","content":"Opens localhost:5173 in the browser","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010007","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200070000","content":"Walks the adoption lifecycle rendered from the bundled fixture","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010008","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200080000","content":"Flips Clone & first run between its two paths, stacked and merged","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010009","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Opens “The adopter’s first hour” and steps through its frames","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010010","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200100000","content":"Runs npm test","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010011","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200110000","content":"Runs node scripts/agent-harness/run.mjs --smoke","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300010012","layer_id":"f0000000-0000-4000-8000-210100010000","step_id":"f0000000-0000-4000-8000-200200120000","content":"Deploys dist/ to any static host — the fallback ships in the bundle","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300020006","layer_id":"f0000000-0000-4000-8000-210100020000","step_id":"f0000000-0000-4000-8000-200200060000","content":"Renders the sample content in no-DB mode, with nothing on the wire","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300020007","layer_id":"f0000000-0000-4000-8000-210100020000","step_id":"f0000000-0000-4000-8000-200200070000","content":"Draws the overview canvas: four phases with the Operate → Map loop arrow","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300020008","layer_id":"f0000000-0000-4000-8000-210100020000","step_id":"f0000000-0000-4000-8000-200200080000","content":"Marks shared columns quiet and divergent columns with the striped wash","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300020009","layer_id":"f0000000-0000-4000-8000-210100020000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Presents the slice as frames, each located on the blueprint","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300030006","layer_id":"f0000000-0000-4000-8000-210100030000","step_id":"f0000000-0000-4000-8000-200200060000","content":"Landing page\nOverview canvas","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300030008","layer_id":"f0000000-0000-4000-8000-210100030000","step_id":"f0000000-0000-4000-8000-200200080000","content":"Stacked compare","picture":null,"description":null,"links":[{"type":"tech_description","label":"Stacked compare","description":"Each path renders as its own band; the column highlight marks where the bands disagree."}]},
    {"id":"f0000000-0000-4000-8000-210300030108","layer_id":"f0000000-0000-4000-8000-210100030000","step_id":"f0000000-0000-4000-8000-200200080000","content":"Merged compare + ledger","picture":null,"description":null,"links":[{"type":"tech_description","label":"Merged compare + ledger","description":"One combined grid per slot: shared cells draw once with member labels over a striped wash; the ledger lists every difference."}],"slot_position":1},
    {"id":"f0000000-0000-4000-8000-210300030009","layer_id":"f0000000-0000-4000-8000-210100030000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Slice focus view\nPresentation mode","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300040003","layer_id":"f0000000-0000-4000-8000-210100040000","step_id":"f0000000-0000-4000-8000-200200030000","content":"Detects missing VITE_SUPABASE_* and switches to the bundled fallback registry","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300040006","layer_id":"f0000000-0000-4000-8000-210100040000","step_id":"f0000000-0000-4000-8000-200200060000","content":"Resolves blueprints synchronously from src/data/blueprintFallbacks.ts","picture":null,"description":null,"links":[{"type":"url","label":"src/data/blueprintFallbacks.ts","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/src/data/blueprintFallbacks.ts"}]},
    {"id":"f0000000-0000-4000-8000-210300040009","layer_id":"f0000000-0000-4000-8000-210100040000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Serves the demo slices from src/data/sliceFallbacks.ts","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300050001","layer_id":"f0000000-0000-4000-8000-210100050000","step_id":"f0000000-0000-4000-8000-200200010000","content":"git clone","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300050002","layer_id":"f0000000-0000-4000-8000-210100050000","step_id":"f0000000-0000-4000-8000-200200020000","content":"npm install","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300050005","layer_id":"f0000000-0000-4000-8000-210100050000","step_id":"f0000000-0000-4000-8000-200200050000","content":"Vite dev server","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300050010","layer_id":"f0000000-0000-4000-8000-210100050000","step_id":"f0000000-0000-4000-8000-200200100000","content":"Vitest — the same suite CI runs","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300050011","layer_id":"f0000000-0000-4000-8000-210100050000","step_id":"f0000000-0000-4000-8000-200200110000","content":"Agent harness (--smoke)","picture":null,"description":null,"links":[{"type":"url","label":"scripts/agent-harness/run.mjs","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/scripts/agent-harness/run.mjs"}]},
    {"id":"f0000000-0000-4000-8000-210300050012","layer_id":"f0000000-0000-4000-8000-210100050000","step_id":"f0000000-0000-4000-8000-200200120000","content":"npm run build\nNetlify (or any static host)","picture":null,"description":null,"links":[{"type":"url","label":"netlify.toml","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/netlify.toml"}]},
    {"id":"f0000000-0000-4000-8000-210300060006","layer_id":"f0000000-0000-4000-8000-210100060000","step_id":"f0000000-0000-4000-8000-200200060000","content":"src/data/sampleBlueprint.ts\nsupabase/seed.sql","picture":null,"description":"One generator emits both artifacts, so the no-DB fallback and the database seed can never drift apart.","links":[{"type":"url","label":"scripts/generate_sample_blueprint.mjs","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/scripts/generate_sample_blueprint.mjs"}]},
    {"id":"f0000000-0000-4000-8000-210300060009","layer_id":"f0000000-0000-4000-8000-210100060000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Demo slices (journey + step)","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-210300060010","layer_id":"f0000000-0000-4000-8000-210100060000","step_id":"f0000000-0000-4000-8000-200200100000","content":"Fixture-pinned Vitest cases","picture":null,"description":null,"links":[]},
  ],
  triggers: [
    {"id":"f0000000-0000-4000-8000-210400010000","source_cell_id":"f0000000-0000-4000-8000-210300010001","target_cell_id":"f0000000-0000-4000-8000-210300010002"},
    {"id":"f0000000-0000-4000-8000-210400020000","source_cell_id":"f0000000-0000-4000-8000-210300010002","target_cell_id":"f0000000-0000-4000-8000-210300010003"},
    {"id":"f0000000-0000-4000-8000-210400030000","source_cell_id":"f0000000-0000-4000-8000-210300010003","target_cell_id":"f0000000-0000-4000-8000-210300010005"},
    {"id":"f0000000-0000-4000-8000-210400040000","source_cell_id":"f0000000-0000-4000-8000-210300010005","target_cell_id":"f0000000-0000-4000-8000-210300010006"},
    {"id":"f0000000-0000-4000-8000-210400050000","source_cell_id":"f0000000-0000-4000-8000-210300010006","target_cell_id":"f0000000-0000-4000-8000-210300010007"},
    {"id":"f0000000-0000-4000-8000-210400060000","source_cell_id":"f0000000-0000-4000-8000-210300010007","target_cell_id":"f0000000-0000-4000-8000-210300010008"},
    {"id":"f0000000-0000-4000-8000-210400070000","source_cell_id":"f0000000-0000-4000-8000-210300010008","target_cell_id":"f0000000-0000-4000-8000-210300010009"},
    {"id":"f0000000-0000-4000-8000-210400080000","source_cell_id":"f0000000-0000-4000-8000-210300010009","target_cell_id":"f0000000-0000-4000-8000-210300010010"},
    {"id":"f0000000-0000-4000-8000-210400090000","source_cell_id":"f0000000-0000-4000-8000-210300010010","target_cell_id":"f0000000-0000-4000-8000-210300010011"},
    {"id":"f0000000-0000-4000-8000-210400100000","source_cell_id":"f0000000-0000-4000-8000-210300010011","target_cell_id":"f0000000-0000-4000-8000-210300010012"},
    {"id":"f0000000-0000-4000-8000-210400110000","source_cell_id":"f0000000-0000-4000-8000-210300050005","target_cell_id":"f0000000-0000-4000-8000-210300020006","label":"localhost:5173"},
    {"id":"f0000000-0000-4000-8000-210400120000","source_cell_id":"f0000000-0000-4000-8000-210300010010","target_cell_id":"f0000000-0000-4000-8000-210300050010"},
    {"id":"f0000000-0000-4000-8000-210400130000","source_cell_id":"f0000000-0000-4000-8000-210300040006","target_cell_id":"f0000000-0000-4000-8000-210300060006","kind":"needs","note":"The no-DB read resolves the generated fixture module; without it a keyless clone renders nothing."},
  ],
}

export const SAMPLE_FIRST_RUN_SUPABASE_PATH_FALLBACK: BlueprintData = {
  path: {"id":"f0000000-0000-4000-8000-220000000000","name":"Supabase run","description":"The same first run backed by a local Supabase stack: migrations, seed, and live reads through the anon key.","note":null,"path_type":"alternative"},
  layers: [
    {"id":"f0000000-0000-4000-8000-220100000000","name":"Journey snapshots","role":"visual","row_position":0},
    {"id":"f0000000-0000-4000-8000-220100010000","name":"Adopter","role":"customer_actions","row_position":1},
    {"id":"f0000000-0000-4000-8000-220100020000","name":"App feedback","role":"frontstage_actions","row_position":2},
    {"id":"f0000000-0000-4000-8000-220100030000","name":"App UI","role":"frontstage_tech","row_position":3},
    {"id":"f0000000-0000-4000-8000-220100040000","name":"Data layer","role":"backstage_actions","row_position":4},
    {"id":"f0000000-0000-4000-8000-220100050000","name":"Terminal & scripts","role":"backstage_tech","row_position":5},
    {"id":"f0000000-0000-4000-8000-220100060000","name":"样例数据 · Sample data","role":"support_systems","row_position":6},
  ],
  steps: [
    {"id":"f0000000-0000-4000-8000-200200010000","name":"Clone the repository","column_position":1},
    {"id":"f0000000-0000-4000-8000-200200020000","name":"Install dependencies","column_position":2},
    {"id":"f0000000-0000-4000-8000-200200030000","name":"Configure the environment","column_position":3},
    {"id":"f0000000-0000-4000-8000-200200040000","name":"Prepare the database","column_position":4},
    {"id":"f0000000-0000-4000-8000-200200050000","name":"Start the dev server","column_position":5},
    {"id":"f0000000-0000-4000-8000-200200060000","name":"Open the app","column_position":6},
    {"id":"f0000000-0000-4000-8000-200200070000","name":"Walk the sample content","column_position":7},
    {"id":"f0000000-0000-4000-8000-200200080000","name":"Compare the sample paths","column_position":8},
    {"id":"f0000000-0000-4000-8000-200200090000","name":"Open a demo slice","column_position":9},
    {"id":"f0000000-0000-4000-8000-200200100000","name":"Run the test suite","column_position":10},
    {"id":"f0000000-0000-4000-8000-200200110000","name":"Smoke the agent harness","column_position":11},
    {"id":"f0000000-0000-4000-8000-200200120000","name":"Deploy a preview","column_position":12},
  ],
  cells: [
    {"id":"f0000000-0000-4000-8000-220300000001","layer_id":"f0000000-0000-4000-8000-220100000000","step_id":"f0000000-0000-4000-8000-200200010000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300000006","layer_id":"f0000000-0000-4000-8000-220100000000","step_id":"f0000000-0000-4000-8000-200200060000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300000008","layer_id":"f0000000-0000-4000-8000-220100000000","step_id":"f0000000-0000-4000-8000-200200080000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300000012","layer_id":"f0000000-0000-4000-8000-220100000000","step_id":"f0000000-0000-4000-8000-200200120000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010001","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200010000","content":"Clones BilLogic/agentic-service-blueprinting from GitHub","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010002","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200020000","content":"Runs npm install","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010003","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200030000","content":"Copies .env.example to .env and keeps it git-ignored","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010004","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200040000","content":"Runs npm run supabase:start, then npm run supabase:reset","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010005","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200050000","content":"Runs npm run dev","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010006","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200060000","content":"Opens localhost:5173 in the browser","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010007","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200070000","content":"Walks the same adoption lifecycle, now served from Postgres","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010008","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200080000","content":"Flips Clone & first run between its two paths, stacked and merged","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010009","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Opens “The adopter’s first hour” and steps through its frames","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010010","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200100000","content":"Runs npm test","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010011","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200110000","content":"Runs node scripts/agent-harness/run.mjs --smoke","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300010012","layer_id":"f0000000-0000-4000-8000-220100010000","step_id":"f0000000-0000-4000-8000-200200120000","content":"Sets VITE_SUPABASE_* at build time, then deploys dist/","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300020006","layer_id":"f0000000-0000-4000-8000-220100020000","step_id":"f0000000-0000-4000-8000-200200060000","content":"Renders the same content from live reads through the anon key","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300020007","layer_id":"f0000000-0000-4000-8000-220100020000","step_id":"f0000000-0000-4000-8000-200200070000","content":"Draws the overview canvas: four phases with the Operate → Map loop arrow","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300020008","layer_id":"f0000000-0000-4000-8000-220100020000","step_id":"f0000000-0000-4000-8000-200200080000","content":"Marks shared columns quiet and divergent columns with the striped wash","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300020009","layer_id":"f0000000-0000-4000-8000-220100020000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Presents the slice as frames, each located on the blueprint","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300030006","layer_id":"f0000000-0000-4000-8000-220100030000","step_id":"f0000000-0000-4000-8000-200200060000","content":"Landing page\nOverview canvas","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300030008","layer_id":"f0000000-0000-4000-8000-220100030000","step_id":"f0000000-0000-4000-8000-200200080000","content":"Stacked compare","picture":null,"description":null,"links":[{"type":"tech_description","label":"Stacked compare","description":"Each path renders as its own band; the column highlight marks where the bands disagree."}]},
    {"id":"f0000000-0000-4000-8000-220300030108","layer_id":"f0000000-0000-4000-8000-220100030000","step_id":"f0000000-0000-4000-8000-200200080000","content":"Merged compare + ledger","picture":null,"description":null,"links":[{"type":"tech_description","label":"Merged compare + ledger","description":"One combined grid per slot: shared cells draw once with member labels over a striped wash; the ledger lists every difference."}],"slot_position":1},
    {"id":"f0000000-0000-4000-8000-220300030009","layer_id":"f0000000-0000-4000-8000-220100030000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Slice focus view\nPresentation mode","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300040003","layer_id":"f0000000-0000-4000-8000-220100040000","step_id":"f0000000-0000-4000-8000-200200030000","content":"Reads VITE_SUPABASE_URL and the anon key from the environment","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300040004","layer_id":"f0000000-0000-4000-8000-220100040000","step_id":"f0000000-0000-4000-8000-200200040000","content":"Applies every migration in supabase/migrations, then runs supabase/seed.sql","picture":null,"description":null,"links":[{"type":"url","label":"supabase/seed.sql","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/supabase/seed.sql"}]},
    {"id":"f0000000-0000-4000-8000-220300040006","layer_id":"f0000000-0000-4000-8000-220100040000","step_id":"f0000000-0000-4000-8000-200200060000","content":"Fetches phases, paths, and cells over PostgREST","picture":null,"description":null,"links":[{"type":"url","label":"src/data/blueprintFallbacks.ts","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/src/data/blueprintFallbacks.ts"}]},
    {"id":"f0000000-0000-4000-8000-220300040009","layer_id":"f0000000-0000-4000-8000-220100040000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Reads slices and slice_items rows seeded by the same generator","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300050001","layer_id":"f0000000-0000-4000-8000-220100050000","step_id":"f0000000-0000-4000-8000-200200010000","content":"git clone","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300050002","layer_id":"f0000000-0000-4000-8000-220100050000","step_id":"f0000000-0000-4000-8000-200200020000","content":"npm install","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300050004","layer_id":"f0000000-0000-4000-8000-220100050000","step_id":"f0000000-0000-4000-8000-200200040000","content":"Supabase CLI\nDocker","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300050005","layer_id":"f0000000-0000-4000-8000-220100050000","step_id":"f0000000-0000-4000-8000-200200050000","content":"Vite dev server","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300050010","layer_id":"f0000000-0000-4000-8000-220100050000","step_id":"f0000000-0000-4000-8000-200200100000","content":"Vitest — the same suite CI runs","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300050011","layer_id":"f0000000-0000-4000-8000-220100050000","step_id":"f0000000-0000-4000-8000-200200110000","content":"Agent harness (--smoke)","picture":null,"description":null,"links":[{"type":"url","label":"scripts/agent-harness/run.mjs","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/scripts/agent-harness/run.mjs"}]},
    {"id":"f0000000-0000-4000-8000-220300050012","layer_id":"f0000000-0000-4000-8000-220100050000","step_id":"f0000000-0000-4000-8000-200200120000","content":"npm run build\nNetlify (or any static host)","picture":null,"description":null,"links":[{"type":"url","label":"netlify.toml","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/netlify.toml"}]},
    {"id":"f0000000-0000-4000-8000-220300060006","layer_id":"f0000000-0000-4000-8000-220100060000","step_id":"f0000000-0000-4000-8000-200200060000","content":"src/data/sampleBlueprint.ts\nsupabase/seed.sql","picture":null,"description":"One generator emits both artifacts, so the no-DB fallback and the database seed can never drift apart.","links":[{"type":"url","label":"scripts/generate_sample_blueprint.mjs","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/scripts/generate_sample_blueprint.mjs"}]},
    {"id":"f0000000-0000-4000-8000-220300060009","layer_id":"f0000000-0000-4000-8000-220100060000","step_id":"f0000000-0000-4000-8000-200200090000","content":"Demo slices (journey + step)","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-220300060010","layer_id":"f0000000-0000-4000-8000-220100060000","step_id":"f0000000-0000-4000-8000-200200100000","content":"Fixture-pinned Vitest cases","picture":null,"description":null,"links":[]},
  ],
  triggers: [
    {"id":"f0000000-0000-4000-8000-220400010000","source_cell_id":"f0000000-0000-4000-8000-220300010001","target_cell_id":"f0000000-0000-4000-8000-220300010002"},
    {"id":"f0000000-0000-4000-8000-220400020000","source_cell_id":"f0000000-0000-4000-8000-220300010002","target_cell_id":"f0000000-0000-4000-8000-220300010003"},
    {"id":"f0000000-0000-4000-8000-220400030000","source_cell_id":"f0000000-0000-4000-8000-220300010003","target_cell_id":"f0000000-0000-4000-8000-220300010004"},
    {"id":"f0000000-0000-4000-8000-220400040000","source_cell_id":"f0000000-0000-4000-8000-220300010004","target_cell_id":"f0000000-0000-4000-8000-220300010005"},
    {"id":"f0000000-0000-4000-8000-220400050000","source_cell_id":"f0000000-0000-4000-8000-220300010005","target_cell_id":"f0000000-0000-4000-8000-220300010006"},
    {"id":"f0000000-0000-4000-8000-220400060000","source_cell_id":"f0000000-0000-4000-8000-220300010006","target_cell_id":"f0000000-0000-4000-8000-220300010007"},
    {"id":"f0000000-0000-4000-8000-220400070000","source_cell_id":"f0000000-0000-4000-8000-220300010007","target_cell_id":"f0000000-0000-4000-8000-220300010008"},
    {"id":"f0000000-0000-4000-8000-220400080000","source_cell_id":"f0000000-0000-4000-8000-220300010008","target_cell_id":"f0000000-0000-4000-8000-220300010009"},
    {"id":"f0000000-0000-4000-8000-220400090000","source_cell_id":"f0000000-0000-4000-8000-220300010009","target_cell_id":"f0000000-0000-4000-8000-220300010010"},
    {"id":"f0000000-0000-4000-8000-220400100000","source_cell_id":"f0000000-0000-4000-8000-220300010010","target_cell_id":"f0000000-0000-4000-8000-220300010011"},
    {"id":"f0000000-0000-4000-8000-220400110000","source_cell_id":"f0000000-0000-4000-8000-220300010011","target_cell_id":"f0000000-0000-4000-8000-220300010012"},
    {"id":"f0000000-0000-4000-8000-220400120000","source_cell_id":"f0000000-0000-4000-8000-220300010004","target_cell_id":"f0000000-0000-4000-8000-220300050004"},
    {"id":"f0000000-0000-4000-8000-220400130000","source_cell_id":"f0000000-0000-4000-8000-220300050005","target_cell_id":"f0000000-0000-4000-8000-220300020006","label":"localhost:5173"},
    {"id":"f0000000-0000-4000-8000-220400140000","source_cell_id":"f0000000-0000-4000-8000-220300010010","target_cell_id":"f0000000-0000-4000-8000-220300050010"},
    {"id":"f0000000-0000-4000-8000-220400150000","source_cell_id":"f0000000-0000-4000-8000-220300040006","target_cell_id":"f0000000-0000-4000-8000-220300040004","kind":"needs","note":"Live reads depend on the migrations and seed having been applied."},
  ],
}

export const SAMPLE_MAP_SERVICE_GUIDED_PATH_FALLBACK: BlueprintData = {
  path: {"id":"f0000000-0000-4000-8000-310000000000","name":"Guided mapping","description":"A full pass from “map our service” to a deployed blueprint, every phase ending at a deterministic gate.","note":null,"path_type":"happy"},
  layers: [
    {"id":"f0000000-0000-4000-8000-310100000000","name":"Journey snapshots","role":"visual","row_position":0},
    {"id":"f0000000-0000-4000-8000-310100010000","name":"Adopter","role":"customer_actions","row_position":1},
    {"id":"f0000000-0000-4000-8000-310100020000","name":"Claude in the IDE","role":"frontstage_actions","row_position":2},
    {"id":"f0000000-0000-4000-8000-310100030000","name":"App preview","role":"frontstage_tech","row_position":3},
    {"id":"f0000000-0000-4000-8000-310100040000","name":"Subagent fleet","role":"backstage_actions","row_position":4},
    {"id":"f0000000-0000-4000-8000-310100050000","name":"Pipeline scripts","role":"backstage_tech","row_position":5},
    {"id":"f0000000-0000-4000-8000-310100060000","name":"References","role":"support_systems","row_position":6},
    {"id":"f0000000-0000-4000-8000-310100070000","name":"Guardrail hooks","role":"support_systems","row_position":7},
  ],
  steps: [
    {"id":"f0000000-0000-4000-8000-300200010000","name":"Invoke sb:map","column_position":1},
    {"id":"f0000000-0000-4000-8000-300200020000","name":"Route by what exists","column_position":2},
    {"id":"f0000000-0000-4000-8000-300200030000","name":"Scope the service","column_position":3},
    {"id":"f0000000-0000-4000-8000-300200040000","name":"Settle the spine","column_position":4},
    {"id":"f0000000-0000-4000-8000-300200050000","name":"Read the sources","column_position":5},
    {"id":"f0000000-0000-4000-8000-300200060000","name":"Draft the structure","column_position":6},
    {"id":"f0000000-0000-4000-8000-300200070000","name":"Fill cells with provenance","column_position":7},
    {"id":"f0000000-0000-4000-8000-300200080000","name":"Validate the blueprint file","column_position":8},
    {"id":"f0000000-0000-4000-8000-300200090000","name":"Preview the render","column_position":9},
    {"id":"f0000000-0000-4000-8000-300200100000","name":"Adversarial review","column_position":10},
    {"id":"f0000000-0000-4000-8000-300200110000","name":"Resolve the findings","column_position":11},
    {"id":"f0000000-0000-4000-8000-300200120000","name":"Sign off per scenario","column_position":12},
    {"id":"f0000000-0000-4000-8000-300200130000","name":"Generate the fallbacks","column_position":13},
    {"id":"f0000000-0000-4000-8000-300200140000","name":"Generate the seed","column_position":14},
    {"id":"f0000000-0000-4000-8000-300200150000","name":"Import and verify","column_position":15},
    {"id":"f0000000-0000-4000-8000-300200160000","name":"Deploy","column_position":16},
  ],
  cells: [
    {"id":"f0000000-0000-4000-8000-310300000001","layer_id":"f0000000-0000-4000-8000-310100000000","step_id":"f0000000-0000-4000-8000-300200010000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300000006","layer_id":"f0000000-0000-4000-8000-310100000000","step_id":"f0000000-0000-4000-8000-300200060000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300000009","layer_id":"f0000000-0000-4000-8000-310100000000","step_id":"f0000000-0000-4000-8000-300200090000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300000012","layer_id":"f0000000-0000-4000-8000-310100000000","step_id":"f0000000-0000-4000-8000-300200120000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300000016","layer_id":"f0000000-0000-4000-8000-310100000000","step_id":"f0000000-0000-4000-8000-300200160000","content":"","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010001","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200010000","content":"Asks for a service to be mapped — from documents, a diagram, or nothing at all","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010003","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200030000","content":"Answers the scoping question: one flow now, or the whole service","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010004","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200040000","content":"Names whose journey runs along the spine","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010006","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200060000","content":"Nods on the proposed step and lane outline before anything is built","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010007","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200070000","content":"Answers per-lane questions as the cells fill in","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010009","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200090000","content":"Reads the rendered draft in the browser","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010011","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200110000","content":"Decides which review findings to accept","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010012","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200120000","content":"Signs off each scenario against its content hash","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300010016","layer_id":"f0000000-0000-4000-8000-310100010000","step_id":"f0000000-0000-4000-8000-300200160000","content":"Shares the deployed URL with the team","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020001","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200010000","content":"Loads the sb:map skill and its elicitation protocol","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020002","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200020000","content":"Routes by what exists: co-create, ingest, translate, or resume","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020003","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200030000","content":"Right-sizes the scope before structuring anything","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020004","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200040000","content":"Settles the spine before drawing lanes","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020005","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200050000","content":"Dispatches document-readers instead of reading sources in its own context","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020006","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200060000","content":"Proposes the outline as plain text and waits for a nod","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020007","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200070000","content":"Writes cells with per-claim provenance, never inventing content","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020008","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200080000","content":"Runs the validator until it exits 0","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020010","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200100000","content":"Dispatches a fresh-context reviewer that never saw the drafting","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020011","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200110000","content":"Fixes accepted findings in the blueprint file","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020012","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200120000","content":"Computes the sign-off hash and records the approval","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020013","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200130000","content":"Generates the no-database fallback module and registers it","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020014","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200140000","content":"Generates the transactional seed","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020015","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200150000","content":"Imports through the service account and verifies by reading back","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300020016","layer_id":"f0000000-0000-4000-8000-310100020000","step_id":"f0000000-0000-4000-8000-300200160000","content":"Deploys, then dispatches the render-checker over the live app","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300030009","layer_id":"f0000000-0000-4000-8000-310100030000","step_id":"f0000000-0000-4000-8000-300200090000","content":"Vite dev server\nOverview canvas\nCell detail panel","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300030015","layer_id":"f0000000-0000-4000-8000-310100030000","step_id":"f0000000-0000-4000-8000-300200150000","content":"Imported scenario, read back live","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300030016","layer_id":"f0000000-0000-4000-8000-310100030000","step_id":"f0000000-0000-4000-8000-300200160000","content":"Deployed static build","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300040005","layer_id":"f0000000-0000-4000-8000-310100040000","step_id":"f0000000-0000-4000-8000-300200050000","content":"document-reader returns structure, keeping raw source text out of the main context","picture":null,"description":null,"links":[{"type":"url","label":"agents/document-reader.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/agents/document-reader.md"}]},
    {"id":"f0000000-0000-4000-8000-310300040010","layer_id":"f0000000-0000-4000-8000-310100040000","step_id":"f0000000-0000-4000-8000-300200100000","content":"blueprint-reviewer returns numbered findings with severities","picture":null,"description":null,"links":[{"type":"url","label":"agents/blueprint-reviewer.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/agents/blueprint-reviewer.md"}]},
    {"id":"f0000000-0000-4000-8000-310300040016","layer_id":"f0000000-0000-4000-8000-310100040000","step_id":"f0000000-0000-4000-8000-300200160000","content":"render-checker walks every scenario and screenshots each view","picture":null,"description":null,"links":[{"type":"url","label":"agents/render-checker.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/agents/render-checker.md"}]},
    {"id":"f0000000-0000-4000-8000-310300050008","layer_id":"f0000000-0000-4000-8000-310100050000","step_id":"f0000000-0000-4000-8000-300200080000","content":"validate_ir.py (stdlib-only)","picture":null,"description":null,"links":[{"type":"url","label":"scripts/validate_ir.py","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/scripts/validate_ir.py"}]},
    {"id":"f0000000-0000-4000-8000-310300050012","layer_id":"f0000000-0000-4000-8000-310100050000","step_id":"f0000000-0000-4000-8000-300200120000","content":"compute_signoff_hash.py","picture":null,"description":null,"links":[{"type":"url","label":"scripts/compute_signoff_hash.py","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/scripts/compute_signoff_hash.py"}]},
    {"id":"f0000000-0000-4000-8000-310300050013","layer_id":"f0000000-0000-4000-8000-310100050000","step_id":"f0000000-0000-4000-8000-300200130000","content":"generate_fallbacks.py --register","picture":null,"description":null,"links":[{"type":"url","label":"scripts/generate_fallbacks.py","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/scripts/generate_fallbacks.py"}]},
    {"id":"f0000000-0000-4000-8000-310300050014","layer_id":"f0000000-0000-4000-8000-310100050000","step_id":"f0000000-0000-4000-8000-300200140000","content":"generate_seed_sql.py","picture":null,"description":null,"links":[{"type":"url","label":"scripts/generate_seed_sql.py","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/scripts/generate_seed_sql.py"}]},
    {"id":"f0000000-0000-4000-8000-310300050015","layer_id":"f0000000-0000-4000-8000-310100050000","step_id":"f0000000-0000-4000-8000-300200150000","content":"Supabase CLI\nPostgREST read-back","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-310300060001","layer_id":"f0000000-0000-4000-8000-310100060000","step_id":"f0000000-0000-4000-8000-300200010000","content":"elicitation-protocol.md","picture":null,"description":null,"links":[{"type":"url","label":"skills/map/references/elicitation-protocol.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/skills/map/references/elicitation-protocol.md"}]},
    {"id":"f0000000-0000-4000-8000-310300060004","layer_id":"f0000000-0000-4000-8000-310100060000","step_id":"f0000000-0000-4000-8000-300200040000","content":"lane-vocabulary.md\nlayer-roles.md","picture":null,"description":null,"links":[{"type":"url","label":"references/layer-roles.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/references/layer-roles.md"}]},
    {"id":"f0000000-0000-4000-8000-310300060006","layer_id":"f0000000-0000-4000-8000-310100060000","step_id":"f0000000-0000-4000-8000-300200060000","content":"data-model.md\nir-schema.json","picture":null,"description":null,"links":[{"type":"url","label":"references/data-model.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/references/data-model.md"}]},
    {"id":"f0000000-0000-4000-8000-310300060016","layer_id":"f0000000-0000-4000-8000-310100060000","step_id":"f0000000-0000-4000-8000-300200160000","content":"deploy-notes.md","picture":null,"description":null,"links":[{"type":"url","label":"skills/map/references/deploy-notes.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/skills/map/references/deploy-notes.md"}]},
    {"id":"f0000000-0000-4000-8000-310300070007","layer_id":"f0000000-0000-4000-8000-310100070000","step_id":"f0000000-0000-4000-8000-300200070000","content":"validate_ir_on_edit.py — re-validates the blueprint file on every edit","picture":null,"description":null,"links":[{"type":"url","label":"hooks/validate_ir_on_edit.py","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/hooks/validate_ir_on_edit.py"}]},
    {"id":"f0000000-0000-4000-8000-310300070015","layer_id":"f0000000-0000-4000-8000-310100070000","step_id":"f0000000-0000-4000-8000-300200150000","content":"secret_guard.py — the service-role key never reaches disk or transcript","picture":null,"description":null,"links":[{"type":"url","label":"hooks/secret_guard.py","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/hooks/secret_guard.py"}]},
  ],
  triggers: [
    {"id":"f0000000-0000-4000-8000-310400010000","source_cell_id":"f0000000-0000-4000-8000-310300010001","target_cell_id":"f0000000-0000-4000-8000-310300010003"},
    {"id":"f0000000-0000-4000-8000-310400020000","source_cell_id":"f0000000-0000-4000-8000-310300010003","target_cell_id":"f0000000-0000-4000-8000-310300010004"},
    {"id":"f0000000-0000-4000-8000-310400030000","source_cell_id":"f0000000-0000-4000-8000-310300010004","target_cell_id":"f0000000-0000-4000-8000-310300010006"},
    {"id":"f0000000-0000-4000-8000-310400040000","source_cell_id":"f0000000-0000-4000-8000-310300010006","target_cell_id":"f0000000-0000-4000-8000-310300010007"},
    {"id":"f0000000-0000-4000-8000-310400050000","source_cell_id":"f0000000-0000-4000-8000-310300010007","target_cell_id":"f0000000-0000-4000-8000-310300010009"},
    {"id":"f0000000-0000-4000-8000-310400060000","source_cell_id":"f0000000-0000-4000-8000-310300010009","target_cell_id":"f0000000-0000-4000-8000-310300010011"},
    {"id":"f0000000-0000-4000-8000-310400070000","source_cell_id":"f0000000-0000-4000-8000-310300010011","target_cell_id":"f0000000-0000-4000-8000-310300010012"},
    {"id":"f0000000-0000-4000-8000-310400080000","source_cell_id":"f0000000-0000-4000-8000-310300010012","target_cell_id":"f0000000-0000-4000-8000-310300010016"},
    {"id":"f0000000-0000-4000-8000-310400090000","source_cell_id":"f0000000-0000-4000-8000-310300020005","target_cell_id":"f0000000-0000-4000-8000-310300040005"},
    {"id":"f0000000-0000-4000-8000-310400100000","source_cell_id":"f0000000-0000-4000-8000-310300020010","target_cell_id":"f0000000-0000-4000-8000-310300040010"},
    {"id":"f0000000-0000-4000-8000-310400110000","source_cell_id":"f0000000-0000-4000-8000-310300010006","target_cell_id":"f0000000-0000-4000-8000-310300020007","label":"nod"},
    {"id":"f0000000-0000-4000-8000-310400120000","source_cell_id":"f0000000-0000-4000-8000-310300020011","target_cell_id":"f0000000-0000-4000-8000-310300020007","label":"rework","note":"Accepted findings send the draft back to cell-filling before a re-validate."},
    {"id":"f0000000-0000-4000-8000-310400130000","source_cell_id":"f0000000-0000-4000-8000-310300020015","target_cell_id":"f0000000-0000-4000-8000-310300020014","kind":"needs","note":"The import consumes the generated seed."},
    {"id":"f0000000-0000-4000-8000-310400140000","source_cell_id":"f0000000-0000-4000-8000-310300010012","target_cell_id":"f0000000-0000-4000-8000-310300050012","kind":"needs","note":"Sign-off is bound to a content hash, not a feeling."},
  ],
}

export const SAMPLE_PRESENT_READOUT_PATH_FALLBACK: BlueprintData = {
  path: {"id":"f0000000-0000-4000-8000-410000000000","name":"Stakeholder readout","description":"From “show me my part” to a presented, exportable slice that still points at its cells.","note":null,"path_type":"happy"},
  layers: [
    {"id":"f0000000-0000-4000-8000-410100000000","name":"Stakeholder","role":"customer_actions","row_position":0},
    {"id":"f0000000-0000-4000-8000-410100010000","name":"sb:slice in the IDE","role":"frontstage_actions","row_position":1},
    {"id":"f0000000-0000-4000-8000-410100020000","name":"Presentation surface","role":"frontstage_tech","row_position":2},
    {"id":"f0000000-0000-4000-8000-410100030000","name":"Reviewer","role":"backstage_actions","row_position":3},
    {"id":"f0000000-0000-4000-8000-410100040000","name":"Slice pipeline","role":"backstage_tech","row_position":4},
    {"id":"f0000000-0000-4000-8000-410100050000","name":"Derived tables","role":"support_systems","row_position":5},
  ],
  steps: [
    {"id":"f0000000-0000-4000-8000-400200010000","name":"Ask for a view","column_position":1},
    {"id":"f0000000-0000-4000-8000-400200020000","name":"Choose the slice type","column_position":2},
    {"id":"f0000000-0000-4000-8000-400200030000","name":"Compose the frames","column_position":3},
    {"id":"f0000000-0000-4000-8000-400200040000","name":"Validate the slice","column_position":4},
    {"id":"f0000000-0000-4000-8000-400200050000","name":"Review the claims","column_position":5},
    {"id":"f0000000-0000-4000-8000-400200060000","name":"Import the slice","column_position":6},
    {"id":"f0000000-0000-4000-8000-400200070000","name":"Enter presentation mode","column_position":7},
    {"id":"f0000000-0000-4000-8000-400200080000","name":"Walk the frames","column_position":8},
    {"id":"f0000000-0000-4000-8000-400200090000","name":"Export to PDF","column_position":9},
  ],
  cells: [
    {"id":"f0000000-0000-4000-8000-410300000001","layer_id":"f0000000-0000-4000-8000-410100000000","step_id":"f0000000-0000-4000-8000-400200010000","content":"Asks for just the part of the service that concerns their team","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300000007","layer_id":"f0000000-0000-4000-8000-410100000000","step_id":"f0000000-0000-4000-8000-400200070000","content":"Watches one frame at a time on the dark stage","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300000008","layer_id":"f0000000-0000-4000-8000-410100000000","step_id":"f0000000-0000-4000-8000-400200080000","content":"Follows the locator showing where each frame sits on the blueprint","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300000009","layer_id":"f0000000-0000-4000-8000-410100000000","step_id":"f0000000-0000-4000-8000-400200090000","content":"Takes the PDF away; the slice still points at the cells it quotes","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300010002","layer_id":"f0000000-0000-4000-8000-410100010000","step_id":"f0000000-0000-4000-8000-400200020000","content":"Picks one of five slice types: journey, step, lane, cell, or custom","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300010003","layer_id":"f0000000-0000-4000-8000-410100010000","step_id":"f0000000-0000-4000-8000-400200030000","content":"Proposes member cells by name, in journey order, and waits for a nod","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300010004","layer_id":"f0000000-0000-4000-8000-410100010000","step_id":"f0000000-0000-4000-8000-400200040000","content":"Runs the slice validator until it exits 0","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300010006","layer_id":"f0000000-0000-4000-8000-410100010000","step_id":"f0000000-0000-4000-8000-400200060000","content":"Imports the slice; items carry cell ids paired with cell keys","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300020007","layer_id":"f0000000-0000-4000-8000-410100020000","step_id":"f0000000-0000-4000-8000-400200070000","content":"Dark stage\nFilmstrip","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300020008","layer_id":"f0000000-0000-4000-8000-410100020000","step_id":"f0000000-0000-4000-8000-400200080000","content":"Blueprint locator","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300020009","layer_id":"f0000000-0000-4000-8000-410100020000","step_id":"f0000000-0000-4000-8000-400200090000","content":"Print / PDF export","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-410300030005","layer_id":"f0000000-0000-4000-8000-410100030000","step_id":"f0000000-0000-4000-8000-400200050000","content":"blueprint-reviewer (slice mode) checks every claim traces to a cited cell","picture":null,"description":null,"links":[{"type":"url","label":"agents/blueprint-reviewer.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/agents/blueprint-reviewer.md"}]},
    {"id":"f0000000-0000-4000-8000-410300040003","layer_id":"f0000000-0000-4000-8000-410100040000","step_id":"f0000000-0000-4000-8000-400200030000","content":"slice_tools.py","picture":null,"description":null,"links":[{"type":"url","label":"skills/slice/scripts/slice_tools.py","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/skills/slice/scripts/slice_tools.py"}]},
    {"id":"f0000000-0000-4000-8000-410300040004","layer_id":"f0000000-0000-4000-8000-410100040000","step_id":"f0000000-0000-4000-8000-400200040000","content":"slice-schema.json","picture":null,"description":null,"links":[{"type":"url","label":"skills/slice/references/slice-schema.json","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/skills/slice/references/slice-schema.json"}]},
    {"id":"f0000000-0000-4000-8000-410300050006","layer_id":"f0000000-0000-4000-8000-410100050000","step_id":"f0000000-0000-4000-8000-400200060000","content":"slices\nslice_items","picture":null,"description":null,"links":[{"type":"tech_description","label":"slice_items","description":"Slice items reference cells softly — uuid arrays paired with cell keys — so a scenario re-import never cascades into a presentation."}]},
  ],
  triggers: [
    {"id":"f0000000-0000-4000-8000-410400010000","source_cell_id":"f0000000-0000-4000-8000-410300000001","target_cell_id":"f0000000-0000-4000-8000-410300000007"},
    {"id":"f0000000-0000-4000-8000-410400020000","source_cell_id":"f0000000-0000-4000-8000-410300000007","target_cell_id":"f0000000-0000-4000-8000-410300000008"},
    {"id":"f0000000-0000-4000-8000-410400030000","source_cell_id":"f0000000-0000-4000-8000-410300000008","target_cell_id":"f0000000-0000-4000-8000-410300000009"},
    {"id":"f0000000-0000-4000-8000-410400040000","source_cell_id":"f0000000-0000-4000-8000-410300010006","target_cell_id":"f0000000-0000-4000-8000-410300020007"},
    {"id":"f0000000-0000-4000-8000-410400050000","source_cell_id":"f0000000-0000-4000-8000-410300010004","target_cell_id":"f0000000-0000-4000-8000-410300040004"},
    {"id":"f0000000-0000-4000-8000-410400060000","source_cell_id":"f0000000-0000-4000-8000-410300010006","target_cell_id":"f0000000-0000-4000-8000-410300010004","kind":"needs","note":"Only a validated slice is importable."},
    {"id":"f0000000-0000-4000-8000-410400070000","source_cell_id":"f0000000-0000-4000-8000-410300010006","target_cell_id":"f0000000-0000-4000-8000-410300030005","kind":"needs","note":"The import waits for the fresh-context claim review to come back clean."},
  ],
}

export const SAMPLE_STEWARD_LOOP_PATH_FALLBACK: BlueprintData = {
  path: {"id":"f0000000-0000-4000-8000-510000000000","name":"Stewardship loop","description":"Audit finding → traced fix → re-import → re-audit; agent sessions answer from the result.","note":null,"path_type":"happy"},
  layers: [
    {"id":"f0000000-0000-4000-8000-510100000000","name":"Steward","role":"customer_actions","row_position":0},
    {"id":"f0000000-0000-4000-8000-510100010000","name":"sb:audit & sb:whatif","role":"frontstage_actions","row_position":1},
    {"id":"f0000000-0000-4000-8000-510100020000","name":"Findings surface","role":"frontstage_tech","row_position":2},
    {"id":"f0000000-0000-4000-8000-510100030000","name":"Auditor fleet","role":"backstage_actions","row_position":3},
    {"id":"f0000000-0000-4000-8000-510100040000","name":"Audit machinery","role":"backstage_tech","row_position":4},
    {"id":"f0000000-0000-4000-8000-510100050000","name":"Check docs","role":"support_systems","row_position":5},
  ],
  steps: [
    {"id":"f0000000-0000-4000-8000-500200010000","name":"Notice drift","column_position":1},
    {"id":"f0000000-0000-4000-8000-500200020000","name":"Run the audit roster","column_position":2},
    {"id":"f0000000-0000-4000-8000-500200030000","name":"Triage the findings","column_position":3},
    {"id":"f0000000-0000-4000-8000-500200040000","name":"Trace a proposed change","column_position":4},
    {"id":"f0000000-0000-4000-8000-500200050000","name":"Decide the fix","column_position":5},
    {"id":"f0000000-0000-4000-8000-500200060000","name":"Update the blueprint file","column_position":6},
    {"id":"f0000000-0000-4000-8000-500200070000","name":"Re-validate","column_position":7},
    {"id":"f0000000-0000-4000-8000-500200080000","name":"Re-import","column_position":8},
    {"id":"f0000000-0000-4000-8000-500200090000","name":"Verify the render","column_position":9},
    {"id":"f0000000-0000-4000-8000-500200100000","name":"Ask the agent","column_position":10},
    {"id":"f0000000-0000-4000-8000-500200110000","name":"Answer from the blueprint","column_position":11},
  ],
  cells: [
    {"id":"f0000000-0000-4000-8000-510300000001","layer_id":"f0000000-0000-4000-8000-510100000000","step_id":"f0000000-0000-4000-8000-500200010000","content":"Notices the service has drifted from what the blueprint says","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300000003","layer_id":"f0000000-0000-4000-8000-510100000000","step_id":"f0000000-0000-4000-8000-500200030000","content":"Triages each finding: accept, dismiss, or resolve","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300000005","layer_id":"f0000000-0000-4000-8000-510100000000","step_id":"f0000000-0000-4000-8000-500200050000","content":"Decides the fix on the traced copy, before anything moves","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300000009","layer_id":"f0000000-0000-4000-8000-510100000000","step_id":"f0000000-0000-4000-8000-500200090000","content":"Checks the re-imported scenario renders as expected","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300000010","layer_id":"f0000000-0000-4000-8000-510100000000","step_id":"f0000000-0000-4000-8000-500200100000","content":"Asks a question in chat instead of opening the canvas","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300010002","layer_id":"f0000000-0000-4000-8000-510100010000","step_id":"f0000000-0000-4000-8000-500200020000","content":"Runs the roster; findings land as triageable rows, not chat opinion","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300010004","layer_id":"f0000000-0000-4000-8000-510100010000","step_id":"f0000000-0000-4000-8000-500200040000","content":"sb:whatif walks trigger and needs edges downstream from the change","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300010006","layer_id":"f0000000-0000-4000-8000-510100010000","step_id":"f0000000-0000-4000-8000-500200060000","content":"Applies the accepted fixes to blueprint.json","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300010007","layer_id":"f0000000-0000-4000-8000-510100010000","step_id":"f0000000-0000-4000-8000-500200070000","content":"Re-runs validate_ir.py until it exits 0","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300010008","layer_id":"f0000000-0000-4000-8000-510100010000","step_id":"f0000000-0000-4000-8000-500200080000","content":"Re-imports; an unchanged scenario hashes to a no-op","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300010011","layer_id":"f0000000-0000-4000-8000-510100010000","step_id":"f0000000-0000-4000-8000-500200110000","content":"Answers with links back to the exact cells it read","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300020003","layer_id":"f0000000-0000-4000-8000-510100020000","step_id":"f0000000-0000-4000-8000-500200030000","content":"Findings list\nStatus chips (open / resolved / dismissed)","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300030002","layer_id":"f0000000-0000-4000-8000-510100030000","step_id":"f0000000-0000-4000-8000-500200020000","content":"One auditor per check, seeing only that check’s doc and the export","picture":null,"description":null,"links":[{"type":"url","label":"agents/auditor.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/agents/auditor.md"}]},
    {"id":"f0000000-0000-4000-8000-510300030004","layer_id":"f0000000-0000-4000-8000-510100030000","step_id":"f0000000-0000-4000-8000-500200040000","content":"impact-tracer returns affected cells and the assumptions the change breaks","picture":null,"description":null,"links":[{"type":"url","label":"agents/impact-tracer.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/agents/impact-tracer.md"}]},
    {"id":"f0000000-0000-4000-8000-510300040002","layer_id":"f0000000-0000-4000-8000-510100040000","step_id":"f0000000-0000-4000-8000-500200020000","content":"audit_tools.py","picture":null,"description":null,"links":[{"type":"url","label":"skills/audit/scripts/audit_tools.py","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/skills/audit/scripts/audit_tools.py"}]},
    {"id":"f0000000-0000-4000-8000-510300040003","layer_id":"f0000000-0000-4000-8000-510100040000","step_id":"f0000000-0000-4000-8000-500200030000","content":"Finding fingerprints — check name + sorted cell keys, so re-runs dedupe","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300040008","layer_id":"f0000000-0000-4000-8000-510100040000","step_id":"f0000000-0000-4000-8000-500200080000","content":"Content-hash idempotence","picture":null,"description":null,"links":[]},
    {"id":"f0000000-0000-4000-8000-510300050002","layer_id":"f0000000-0000-4000-8000-510100050000","step_id":"f0000000-0000-4000-8000-500200020000","content":"check-gap-sweep.md\ncheck-jargon-lint.md\ncheck-channel-conflict.md","picture":null,"description":"Three of the roster’s eight checks; the audit playbook lists them all.","links":[{"type":"url","label":"skills/audit/references/check-gap-sweep.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/skills/audit/references/check-gap-sweep.md"},{"type":"url","label":"references/audit-playbook.md","url":"https://github.com/BilLogic/agentic-service-blueprinting/blob/main/references/audit-playbook.md"}]},
  ],
  triggers: [
    {"id":"f0000000-0000-4000-8000-510400010000","source_cell_id":"f0000000-0000-4000-8000-510300000001","target_cell_id":"f0000000-0000-4000-8000-510300000003"},
    {"id":"f0000000-0000-4000-8000-510400020000","source_cell_id":"f0000000-0000-4000-8000-510300000003","target_cell_id":"f0000000-0000-4000-8000-510300000005"},
    {"id":"f0000000-0000-4000-8000-510400030000","source_cell_id":"f0000000-0000-4000-8000-510300000005","target_cell_id":"f0000000-0000-4000-8000-510300000009"},
    {"id":"f0000000-0000-4000-8000-510400040000","source_cell_id":"f0000000-0000-4000-8000-510300000009","target_cell_id":"f0000000-0000-4000-8000-510300000010"},
    {"id":"f0000000-0000-4000-8000-510400050000","source_cell_id":"f0000000-0000-4000-8000-510300010002","target_cell_id":"f0000000-0000-4000-8000-510300030002"},
    {"id":"f0000000-0000-4000-8000-510400060000","source_cell_id":"f0000000-0000-4000-8000-510300000003","target_cell_id":"f0000000-0000-4000-8000-510300010004"},
    {"id":"f0000000-0000-4000-8000-510400070000","source_cell_id":"f0000000-0000-4000-8000-510300010008","target_cell_id":"f0000000-0000-4000-8000-510300010002","label":"re-audit","note":"A re-import sends the loop back to the roster: audit, fix, import, verify — the Operate phase in miniature."},
    {"id":"f0000000-0000-4000-8000-510400080000","source_cell_id":"f0000000-0000-4000-8000-510300010008","target_cell_id":"f0000000-0000-4000-8000-510300010007","kind":"needs","note":"Only a re-validated file is re-importable."},
  ],
}

/** Path fallbacks per scenario, in picker order. */
export const SAMPLE_BLUEPRINTS_BY_SCENARIO: Record<string, BlueprintData[]> = {
  'f0000000-0000-4000-8000-100000000001': [
    SAMPLE_DISCOVER_KIT_VISIT_PATH_FALLBACK,
  ],
  'f0000000-0000-4000-8000-200000000001': [
    SAMPLE_FIRST_RUN_NODB_PATH_FALLBACK,
    SAMPLE_FIRST_RUN_SUPABASE_PATH_FALLBACK,
  ],
  'f0000000-0000-4000-8000-300000000001': [
    SAMPLE_MAP_SERVICE_GUIDED_PATH_FALLBACK,
  ],
  'f0000000-0000-4000-8000-400000000001': [
    SAMPLE_PRESENT_READOUT_PATH_FALLBACK,
  ],
  'f0000000-0000-4000-8000-500000000001': [
    SAMPLE_STEWARD_LOOP_PATH_FALLBACK,
  ],
}

/**
 * Demo slices over the sample content — the zero-config content for the
 * slices surface (sidebar groups, focus view, presentation). Same shape as
 * the database rows, so the read hooks fall back to them verbatim.
 */
export const SAMPLE_DEMO_SLICES: Slice[] = [
  {"id":"f0000000-0000-4000-8000-000500010000","service_lifecycle_id":"f0000000-0000-4000-8000-000000000010","title":"The adopter’s first hour","description":"From git clone to a green harness smoke, on the no-database path — the hour the template promises to anyone with npm.","actor":"Adopter","slice_type":"journey","origin":"generated","locale":"en","position":1,"created_by":null,"created_at":"2026-08-18T00:00:00+00:00","updated_at":"2026-08-18T00:00:00+00:00"},
  {"id":"f0000000-0000-4000-8000-000500020000","service_lifecycle_id":"f0000000-0000-4000-8000-000000000010","title":"The sign-off moment","description":"One step of Map your service read vertically: who approves a scenario, and what binds the approval.","actor":null,"slice_type":"step","origin":"generated","locale":"en","position":2,"created_by":null,"created_at":"2026-08-18T00:00:00+00:00","updated_at":"2026-08-18T00:00:00+00:00"},
]

export const SAMPLE_DEMO_SLICE_ITEMS: Record<string, SliceItem[]> = {
  'f0000000-0000-4000-8000-000500010000': [
    {"id":"f0000000-0000-4000-8000-000600010001","slice_id":"f0000000-0000-4000-8000-000500010000","position":1,"caption":"Clone and install","narrative":"Two commands stand between the repository and a working checkout.","created_by":null,"illustration":null,"cell_ids":["f0000000-0000-4000-8000-210300010001","f0000000-0000-4000-8000-210300010002"],"cell_keys":["blueprint-kit-adoption/adopt/clone-first-run/no-database-run/adopter/clone-the-repository","blueprint-kit-adoption/adopt/clone-first-run/no-database-run/adopter/install-dependencies"],"created_at":"2026-08-18T00:00:00+00:00","updated_at":"2026-08-18T00:00:00+00:00"},
    {"id":"f0000000-0000-4000-8000-000600010002","slice_id":"f0000000-0000-4000-8000-000500010000","position":2,"caption":"First light","narrative":"With no environment at all, the dev server renders the bundled sample content.","created_by":null,"illustration":null,"cell_ids":["f0000000-0000-4000-8000-210300010005","f0000000-0000-4000-8000-210300010006"],"cell_keys":["blueprint-kit-adoption/adopt/clone-first-run/no-database-run/adopter/start-the-dev-server","blueprint-kit-adoption/adopt/clone-first-run/no-database-run/adopter/open-the-app"],"created_at":"2026-08-18T00:00:00+00:00","updated_at":"2026-08-18T00:00:00+00:00"},
    {"id":"f0000000-0000-4000-8000-000600010003","slice_id":"f0000000-0000-4000-8000-000500010000","position":3,"caption":"Prove it works","narrative":"The test suite and the agent-harness smoke run green on a fresh clone.","created_by":null,"illustration":null,"cell_ids":["f0000000-0000-4000-8000-210300010010","f0000000-0000-4000-8000-210300010011"],"cell_keys":["blueprint-kit-adoption/adopt/clone-first-run/no-database-run/adopter/run-the-test-suite","blueprint-kit-adoption/adopt/clone-first-run/no-database-run/adopter/smoke-the-agent-harness"],"created_at":"2026-08-18T00:00:00+00:00","updated_at":"2026-08-18T00:00:00+00:00"},
  ],
  'f0000000-0000-4000-8000-000500020000': [
    {"id":"f0000000-0000-4000-8000-000600020001","slice_id":"f0000000-0000-4000-8000-000500020000","position":1,"caption":"Who approves","narrative":"The adopter signs off each scenario; Claude records the approval against a hash, not a feeling.","created_by":null,"illustration":null,"cell_ids":["f0000000-0000-4000-8000-310300010012","f0000000-0000-4000-8000-310300020012"],"cell_keys":["blueprint-kit-adoption/map/map-your-service/guided-mapping/adopter/sign-off-per-scenario","blueprint-kit-adoption/map/map-your-service/guided-mapping/claude-in-the-ide/sign-off-per-scenario"],"created_at":"2026-08-18T00:00:00+00:00","updated_at":"2026-08-18T00:00:00+00:00"},
    {"id":"f0000000-0000-4000-8000-000600020002","slice_id":"f0000000-0000-4000-8000-000500020000","position":2,"caption":"What binds it","narrative":"compute_signoff_hash.py turns the scenario content into the hash the approval records.","created_by":null,"illustration":null,"cell_ids":["f0000000-0000-4000-8000-310300050012"],"cell_keys":["blueprint-kit-adoption/map/map-your-service/guided-mapping/pipeline-scripts/sign-off-per-scenario"],"created_at":"2026-08-18T00:00:00+00:00","updated_at":"2026-08-18T00:00:00+00:00"},
  ],
}
